//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.Admin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Admin.IAdmin")]
    public interface IAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/Login", ReplyAction="http://tempuri.org/IAdmin/LoginResponse")]
        void Login();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/Login", ReplyAction="http://tempuri.org/IAdmin/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/AllStations", ReplyAction="http://tempuri.org/IAdmin/AllStationsResponse")]
        DomainModel.Models.Station[] AllStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/AllStations", ReplyAction="http://tempuri.org/IAdmin/AllStationsResponse")]
        System.Threading.Tasks.Task<DomainModel.Models.Station[]> AllStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/Add", ReplyAction="http://tempuri.org/IAdmin/AddResponse")]
        DomainModel.Models.Station Add(string newStationText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/Add", ReplyAction="http://tempuri.org/IAdmin/AddResponse")]
        System.Threading.Tasks.Task<DomainModel.Models.Station> AddAsync(string newStationText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ChangeStation", ReplyAction="http://tempuri.org/IAdmin/ChangeStationResponse")]
        bool ChangeStation(DomainModel.Models.Station station, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ChangeStation", ReplyAction="http://tempuri.org/IAdmin/ChangeStationResponse")]
        System.Threading.Tasks.Task<bool> ChangeStationAsync(DomainModel.Models.Station station, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ChangeStation2", ReplyAction="http://tempuri.org/IAdmin/ChangeStation2Response")]
        bool ChangeStation2(DomainModel.Models.Station station, bool archivalChecked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ChangeStation2", ReplyAction="http://tempuri.org/IAdmin/ChangeStation2Response")]
        System.Threading.Tasks.Task<bool> ChangeStation2Async(DomainModel.Models.Station station, bool archivalChecked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/AddNewConnection", ReplyAction="http://tempuri.org/IAdmin/AddNewConnectionResponse")]
        bool AddNewConnection(DomainModel.Models.Station departureStation, DomainModel.Models.Station arrivalStation, int valueHour, int valueMinute, int price, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/AddNewConnection", ReplyAction="http://tempuri.org/IAdmin/AddNewConnectionResponse")]
        System.Threading.Tasks.Task<bool> AddNewConnectionAsync(DomainModel.Models.Station departureStation, DomainModel.Models.Station arrivalStation, int valueHour, int valueMinute, int price, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/Find", ReplyAction="http://tempuri.org/IAdmin/FindResponse")]
        DomainModel.Models.ConnectionDefinition[] Find(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, int price, int hour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/Find", ReplyAction="http://tempuri.org/IAdmin/FindResponse")]
        System.Threading.Tasks.Task<DomainModel.Models.ConnectionDefinition[]> FindAsync(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, int price, int hour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/AllConnections", ReplyAction="http://tempuri.org/IAdmin/AllConnectionsResponse")]
        DomainModel.Models.ConnectionDefinition[] AllConnections();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/AllConnections", ReplyAction="http://tempuri.org/IAdmin/AllConnectionsResponse")]
        System.Threading.Tasks.Task<DomainModel.Models.ConnectionDefinition[]> AllConnectionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/UpdateConnection", ReplyAction="http://tempuri.org/IAdmin/UpdateConnectionResponse")]
        bool UpdateConnection(DomainModel.Models.ConnectionDefinition cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/UpdateConnection", ReplyAction="http://tempuri.org/IAdmin/UpdateConnectionResponse")]
        System.Threading.Tasks.Task<bool> UpdateConnectionAsync(DomainModel.Models.ConnectionDefinition cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/MakeArchival", ReplyAction="http://tempuri.org/IAdmin/MakeArchivalResponse")]
        bool MakeArchival(DomainModel.Models.ConnectionDefinition cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/MakeArchival", ReplyAction="http://tempuri.org/IAdmin/MakeArchivalResponse")]
        System.Threading.Tasks.Task<bool> MakeArchivalAsync(DomainModel.Models.ConnectionDefinition cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/AddNewConnections", ReplyAction="http://tempuri.org/IAdmin/AddNewConnectionsResponse")]
        bool AddNewConnections(DomainModel.Models.ConnectionDefinition connectionDefinition, System.DateTime value, System.DateTime dateTime, int days, int h, int m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/AddNewConnections", ReplyAction="http://tempuri.org/IAdmin/AddNewConnectionsResponse")]
        System.Threading.Tasks.Task<bool> AddNewConnectionsAsync(DomainModel.Models.ConnectionDefinition connectionDefinition, System.DateTime value, System.DateTime dateTime, int days, int h, int m);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminChannel : UnitTest.Admin.IAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminClient : System.ServiceModel.ClientBase<UnitTest.Admin.IAdmin>, UnitTest.Admin.IAdmin {
        
        public AdminClient() {
        }
        
        public AdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Login() {
            base.Channel.Login();
        }
        
        public System.Threading.Tasks.Task LoginAsync() {
            return base.Channel.LoginAsync();
        }
        
        public DomainModel.Models.Station[] AllStations() {
            return base.Channel.AllStations();
        }
        
        public System.Threading.Tasks.Task<DomainModel.Models.Station[]> AllStationsAsync() {
            return base.Channel.AllStationsAsync();
        }
        
        public DomainModel.Models.Station Add(string newStationText) {
            return base.Channel.Add(newStationText);
        }
        
        public System.Threading.Tasks.Task<DomainModel.Models.Station> AddAsync(string newStationText) {
            return base.Channel.AddAsync(newStationText);
        }
        
        public bool ChangeStation(DomainModel.Models.Station station, string text) {
            return base.Channel.ChangeStation(station, text);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeStationAsync(DomainModel.Models.Station station, string text) {
            return base.Channel.ChangeStationAsync(station, text);
        }
        
        public bool ChangeStation2(DomainModel.Models.Station station, bool archivalChecked) {
            return base.Channel.ChangeStation2(station, archivalChecked);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeStation2Async(DomainModel.Models.Station station, bool archivalChecked) {
            return base.Channel.ChangeStation2Async(station, archivalChecked);
        }
        
        public bool AddNewConnection(DomainModel.Models.Station departureStation, DomainModel.Models.Station arrivalStation, int valueHour, int valueMinute, int price, string name) {
            return base.Channel.AddNewConnection(departureStation, arrivalStation, valueHour, valueMinute, price, name);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewConnectionAsync(DomainModel.Models.Station departureStation, DomainModel.Models.Station arrivalStation, int valueHour, int valueMinute, int price, string name) {
            return base.Channel.AddNewConnectionAsync(departureStation, arrivalStation, valueHour, valueMinute, price, name);
        }
        
        public DomainModel.Models.ConnectionDefinition[] Find(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, int price, int hour) {
            return base.Channel.Find(departure, arrival, price, hour);
        }
        
        public System.Threading.Tasks.Task<DomainModel.Models.ConnectionDefinition[]> FindAsync(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, int price, int hour) {
            return base.Channel.FindAsync(departure, arrival, price, hour);
        }
        
        public DomainModel.Models.ConnectionDefinition[] AllConnections() {
            return base.Channel.AllConnections();
        }
        
        public System.Threading.Tasks.Task<DomainModel.Models.ConnectionDefinition[]> AllConnectionsAsync() {
            return base.Channel.AllConnectionsAsync();
        }
        
        public bool UpdateConnection(DomainModel.Models.ConnectionDefinition cd) {
            return base.Channel.UpdateConnection(cd);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateConnectionAsync(DomainModel.Models.ConnectionDefinition cd) {
            return base.Channel.UpdateConnectionAsync(cd);
        }
        
        public bool MakeArchival(DomainModel.Models.ConnectionDefinition cd) {
            return base.Channel.MakeArchival(cd);
        }
        
        public System.Threading.Tasks.Task<bool> MakeArchivalAsync(DomainModel.Models.ConnectionDefinition cd) {
            return base.Channel.MakeArchivalAsync(cd);
        }
        
        public bool AddNewConnections(DomainModel.Models.ConnectionDefinition connectionDefinition, System.DateTime value, System.DateTime dateTime, int days, int h, int m) {
            return base.Channel.AddNewConnections(connectionDefinition, value, dateTime, days, h, m);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewConnectionsAsync(DomainModel.Models.ConnectionDefinition connectionDefinition, System.DateTime value, System.DateTime dateTime, int days, int h, int m) {
            return base.Channel.AddNewConnectionsAsync(connectionDefinition, value, dateTime, days, h, m);
        }
    }
}
